### ISSUE TITLE
最好官方能在dart-lang里面维护一套中文的版本

### ISSUE THREAD

**Issue by lishizhi** [dartchina/site-www-cn#39]
辛苦了，翻译得特别好，我觉得我们可以去官方提意见，希望能在dart-lang里面维护一套中文版本，这样才能长久，现在已经有几个这样的中文翻译库了，不过是无疾而终。

**Comment by amisare** [comment]
嗯，这确实是一个很不错的注意。
但是，这里面涉及到的不只是简简单的在dart-lang加入一份中文版，编程语言一旦推出就会涉及到全球化问题。 其次，一旦有中文版加入，会涉及到更多的版本加入，这样官网的维护压力就会很大。
不过话说回来，要是有机会加入，也需要有个完善得的中文站，目前站点还存在很多未翻译章节。

现在的情况，dartchina 的 dartdoc.cn 已经被加入到 dartdev.org 中作为中文站的链接。

目前 dartchina 在积极的保持与官方同步，并完善翻译中，在此也欢迎相关爱好者加入☺

**Comment by lishizhi** [comment]
如果官方维护是最好的，如果官方不同意的话，我建议合并到 CFUG (筹) 的 dartlang-cn 项目中去，或者替换掉dartlang-cn，翻译文档是件浩大的功能，非常辛苦，我希望社区不要重复翻译

**Comment by amisare** [comment]
今天在 github 上看了下 CFUG 应该最近成立的组织，同时还有 google 员工的影子，而且组织翻译方式要比我现在的方式好很多，我今天先会尝试在 github 上和 CFUG 沟通下，如果他们有意愿，我也愿意将本仓库合并到 CFUG 。

**Comment by lishizhi** [comment]
问题已解决
